// Generated by CoffeeScript 1.10.0
var _ = require('lodash');
var path = require('path');
var webpack = require('webpack');

module.exports = {
  entry: {
    index:[
      'webpack-hot-middleware/client?reload=true',
      './app/components/ReactApp.jsx'
    ]
  },
  output: {
    path: path.join(__dirname, './dist'),
    filename: '[name].js',
    libraryTarget: 'commonjs2'
  },

  externals: [
    function(context, request, cb) {
      var isExternal;
      isExternal = request.match(/^[a-z][a-z\/\.\-0-9]*$/i) && !request.match(/^react-routing/) && !context.match(/[\\\/]react-routing/);
      cb(null, Boolean(isExternal));
    }
  ],
  
  module: {
    loaders: [
      {
        test: /\.jsx$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel',
        query: {
            presets: ['es2015']
        }
      },
      { test: /\.css$/, loader: 'style-loader!css-loader' },
      { test: /\.js$/, loader: 'jsx-loader?harmony' },
      { test: /\.scss$/, loader: 'style!css!sass?sourceMap'},
      { test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192'}
    ]
  },
  plugins:[
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
  ]
}
