// Generated by CoffeeScript 1.10.0
var _, generateAppConfig, generateConfig, generateServerConfig, loaders, path, webpack;

_ = require('lodash');

path = require('path');

webpack = require('webpack');


module.exports = (function(_this) {
    var serverConfig;

    serverConfig = {
      entry: {
        index:['webpack-dev-server/client?http://127.0.0.1:9090', 'webpack/hot/only-dev-server','./app/components/ReactApp.jsx']
      },
      output: {
        path: path.join(__dirname, './assest'),
        filename:'[name].js',
        chunkFilename:'[chunkhash:8].chunk.js',
        hotUpdateChunkFilename:'[id].js',
        publicPath: "http://127.0.0.1:9090/static/",
      },
      target: 'node',
      externals: [
        function(context, request, cb) {
          var isExternal;
          isExternal = request.match(/^[a-z][a-z\/\.\-0-9]*$/i) && !request.match(/^react-routing/) && !context.match(/[\\\/]react-routing/);
          cb(null, Boolean(isExternal));
        }
      ],
      node: {
        console: false,
        global: false,
        process: false,
        Buffer: false,
        __filename: false,
        __dirname: false
      },
      module: {
        loaders: [
                { test: /\.css$/, loader: 'style-loader!css-loader' },
                { test: /\.js$/, loader: 'jsx-loader?harmony' },
                { test: /\.scss$/, loader: 'style!css!sass?sourceMap'},
                { test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192'},
                {test: /\.jsx?$/, loader: 'babel?presets[]=react,presets[]=es2015'}
            ]
      },
    plugins:[
      new webpack.HotModuleReplacementPlugin(),
    ],
    }
    return serverConfig;
})(this);
